version: '3'
services:
  db:
    image: lmmdock/postgres-multi
    container_name: multidb-pg
    environment:
      POSTGRES_USERS: "multiUser1:developerPass"
      POSTGRES_DATABASES: "rails_multidb_development:multiUser1"
    ports:
      - '5432:5432'
    expose:
      - 5432

